<?php
/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detailed description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'help' => null,
    'silentExitOnException' => null,
    'sourcePath' => './src',
    'messagePath' => './src/messages',
    'languages' => [
        'af', 'ar', 'az',
        'be', 'bg', 'bs',
        'ca', 'cs',
        'da', 'de',
        'el', 'es', 'et',
        'fa', 'fi', 'fr',
        'he', 'hi', 'hr', 'hu', 'hy',
        'id', 'it',
        'ja',
        'ka', 'kk', 'ko', 'kz',
        'lt', 'lv',
        'ms',
        'nb-NO', 'nl',
        'pl', 'pt', 'pt-BR',
        'ro', 'ru',
        'sk', 'sl', 'sr', 'sr-Latn', 'sv',
        'tg', 'th', 'tr',
        'uk', 'uz',
        'vi',
        'zn-CN', 'zn-TW',
    ],
    'translator' => 'Yii::t',
    'sort' => false,
    'overwrite' => true,
    'removeUnused' => false,
    'markUnused' => true,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/messages',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',
    'db' => 'db',
    'sourceMessageTable' => '{{%source_message}}',
    'messageTable' => '{{%message}}',
    'catalog' => 'messages',
    'ignoreCategories' => [],
    'phpFileHeader' => '',
    'phpDocBlock' => null,
];
